routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return view('auth.login');
});
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::resource('autos', App\Http\Controllers\AutoController::class);
    Route::get('/compFoto/{id}', [App\Http\Controllers\AutoController::class, 'downloadFoto'])->name('compFoto');

    Route::resource('discoDuros', App\Http\Controllers\DiscoDuroController::class);

    Route::resource('marcaEquipos', App\Http\Controllers\MarcaEquipoController::class);

    Route::resource('modeloEquipos', App\Http\Controllers\ModeloEquipoController::class);

    Route::resource('rams', App\Http\Controllers\RamController::class);

    Route::resource('tipoEquipos', App\Http\Controllers\TipoEquipoController::class);

    Route::resource('documentoAutos', App\Http\Controllers\DocumentoAutoController::class);

    Route::resource('empleados', App\Http\Controllers\EmpleadoController::class);

    Route::resource('equipos', App\Http\Controllers\EquipoController::class);

    Route::resource('mantenimientoAutos', App\Http\Controllers\MantenimientoAutoController::class);

    Route::resource('proyectos', App\Http\Controllers\ProyectoController::class);

    Route::resource('tallers', App\Http\Controllers\TallerController::class);

    Route::resource('tenencias', App\Http\Controllers\TenenciaController::class);

    Route::resource('usuarios', App\Http\Controllers\UsuarioController::class);

    Route::resource('verificacions', App\Http\Controllers\VerificacionController::class);

    Route::resource('arrendadoras', App\Http\Controllers\ArrendadoraController::class);

    Route::resource('contratos', App\Http\Controllers\ContratoController::class);

    Route::get('/tarjeton/{id}', [App\Http\Controllers\DocumentoAutoController::class, 'downloadTarjeton'])->name('tarjeton');

    Route::get('/factura/{id}', [App\Http\Controllers\DocumentoAutoController::class, 'downloadfactura'])->name('factura');
    Route::get('/responsivaempleado/{id}', [App\Http\Controllers\DocumentoAutoController::class, 'downloadresponsivaempleado'])->name('responsivaempleado');
    Route::get('/ultimatenencia/{id}', [App\Http\Controllers\DocumentoAutoController::class, 'downloadultimatenencia'])->name('ultimatenencia');
    Route::get('/ultimaverificacion/{id}', [App\Http\Controllers\DocumentoAutoController::class, 'downloadultimaverificacion'])->name('ultimaverificacion');

});

app/Models/TipoEquipo.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class TipoEquipo
 * @package App\Models
 * @version June 17, 2021, 5:28 am UTC
 *
 * @property string $tipoEquipo
 */
class TipoEquipo extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'cat_tiposEquipos';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'tipoEquipo'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'tipoEquipo' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'tipoEquipo' => 'nullable|string|max:45',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'deleted_at' => 'nullable'
    ];

    public function autos()
	{
		return $this->hasMany(Auto::class, 'idTipo');
	}

	public function cat_marcas_equipos()
	{
		return $this->hasMany(CatMarcasEquipo::class, 'id_tipoEquipo');
	}

	public function equipos()
	{
		return $this->hasMany(Equipo::class, 'idTipoEquipo');
	}
}

app/Http/Controllers/TipoEquipoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTipoEquipoRequest;
use App\Http\Requests\UpdateTipoEquipoRequest;
use App\Repositories\TipoEquipoRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class TipoEquipoController extends AppBaseController
{
    /** @var  TipoEquipoRepository */
    private $tipoEquipoRepository;

    public function __construct(TipoEquipoRepository $tipoEquipoRepo)
    {
        $this->tipoEquipoRepository = $tipoEquipoRepo;
    }

    /**
     * Display a listing of the TipoEquipo.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $tipoEquipos = $this->tipoEquipoRepository->all();

        return view('tipo_equipos.index')
            ->with('tipoEquipos', $tipoEquipos);
    }

    /**
     * Show the form for creating a new TipoEquipo.
     *
     * @return Response
     */
    public function create()
    {
        return view('tipo_equipos.create');
    }

    /**
     * Store a newly created TipoEquipo in storage.
     *
     * @param CreateTipoEquipoRequest $request
     *
     * @return Response
     */
    public function store(CreateTipoEquipoRequest $request)
    {
        $input = $request->all();

        $tipoEquipo = $this->tipoEquipoRepository->create($input);

        Flash::success('Tipo Equipo saved successfully.');

        return redirect(route('tipoEquipos.index'));
    }

    /**
     * Display the specified TipoEquipo.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $tipoEquipo = $this->tipoEquipoRepository->find($id);

        if (empty($tipoEquipo)) {
            Flash::error('Tipo Equipo not found');

            return redirect(route('tipoEquipos.index'));
        }

        return view('tipo_equipos.show')->with('tipoEquipo', $tipoEquipo);
    }

    /**
     * Show the form for editing the specified TipoEquipo.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $tipoEquipo = $this->tipoEquipoRepository->find($id);

        if (empty($tipoEquipo)) {
            Flash::error('Tipo Equipo not found');

            return redirect(route('tipoEquipos.index'));
        }

        return view('tipo_equipos.edit')->with('tipoEquipo', $tipoEquipo);
    }

    /**
     * Update the specified TipoEquipo in storage.
     *
     * @param int $id
     * @param UpdateTipoEquipoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTipoEquipoRequest $request)
    {
        $tipoEquipo = $this->tipoEquipoRepository->find($id);

        if (empty($tipoEquipo)) {
            Flash::error('Tipo Equipo not found');

            return redirect(route('tipoEquipos.index'));
        }

        $tipoEquipo = $this->tipoEquipoRepository->update($request->all(), $id);

        Flash::success('Tipo Equipo updated successfully.');

        return redirect(route('tipoEquipos.index'));
    }

    /**
     * Remove the specified TipoEquipo from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $tipoEquipo = $this->tipoEquipoRepository->find($id);

        if (empty($tipoEquipo)) {
            Flash::error('Tipo Equipo not found');

            return redirect(route('tipoEquipos.index'));
        }

        $this->tipoEquipoRepository->delete($id);

        Flash::success('Tipo Equipo deleted successfully.');

        return redirect(route('tipoEquipos.index'));
    }
}

resources/views/tipo_equipos/create.blade.php
@extends('layouts.app')
@section('title')
    Create Tipo Equipo
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="m-0 page__heading">Nuevo Tipo Equipo</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('tipoEquipos.index') }}" class="btn btn-primary">Volver</a>
            </div>
        </div>
        <div class="content">
            @include('stisla-templates::common.errors')
            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body ">
                                {!! Form::open(['route' => 'tipoEquipos.store']) !!}
                                <div class="row">
                                    @include('tipo_equipos.fields')
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/tipo_equipos/edit.blade.php
@extends('layouts.app')
@section('title')
    Edit Tipo Equipo
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="m-0 page__heading">Editar Tipo Equipo</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('tipoEquipos.index') }}" class="btn btn-primary">Volver</a>
            </div>
        </div>
        <div class="content">
            @include('stisla-templates::common.errors')
            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body ">
                                {!! Form::model($tipoEquipo, ['route' => ['tipoEquipos.update', $tipoEquipo->id], 'method' => 'patch']) !!}
                                <div class="row">
                                    @include('tipo_equipos.fields')
                                </div>

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/tipo_equipos/fields.blade.php
<!-- Tipoequipo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tipoEquipo', 'Tipo equipo:') !!}
    {!! Form::text('tipoEquipo', null, ['class' => 'form-control','maxlength' => 45,'maxlength' => 45]) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Enviar', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('tipoEquipos.index') }}" class="btn btn-light">Cancelar</a>
</div>

resources/views/tipo_equipos/index.blade.php
@extends('layouts.app')
@section('title')
    Tipo Equipos 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Tipo Equipos</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('tipoEquipos.create')}}" class="btn btn-primary form-btn">Tipo Equipo <i class="fas fa-plus"></i></a>
            </div>
        </div>
    <div class="section-body">
       <div class="card">
            <div class="card-body">
                @include('tipo_equipos.table')
            </div>
       </div>
   </div>
    
    </section>
@endsection

resources/views/tipo_equipos/show.blade.php
@extends('layouts.app')
@section('title')
    Tipo Equipo Details 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
        <h1>Tipo Equipo Details</h1>
        <div class="section-header-breadcrumb">
            <a href="{{ route('tipoEquipos.index') }}"
                 class="btn btn-primary form-btn float-right">Back</a>
        </div>
      </div>
   @include('stisla-templates::common.errors')
    <div class="section-body">
           <div class="card">
            <div class="card-body">
                    @include('tipo_equipos.show_fields')
            </div>
            </div>
    </div>
    </section>
@endsection

resources/views/tipo_equipos/show_fields.blade.php
<!-- Tipoequipo Field -->
<div class="form-group">
    {!! Form::label('tipoEquipo', 'Tipoequipo:') !!}
    <p>{{ $tipoEquipo->tipoEquipo }}</p>
</div>

resources/views/tipo_equipos/table.blade.php
<div class="table-responsive">
    <table class="table" id="dtBasicExample">
        <thead>
            <tr>
                <th>Tipo equipo</th>
                <th>Acción</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($tipoEquipos as $tipoEquipo)
                <tr>
                    <td>{{ $tipoEquipo->tipoEquipo }}</td>
                    <td class="text-center ">
                        {!! Form::open(['route' => ['tipoEquipos.destroy', $tipoEquipo->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                            {{--<a href="{!! route('tipoEquipos.show', [$tipoEquipo->id]) !!}" class='btn btn-light action-btn '><i
                                    class="fa fa-eye"></i></a>--}}
                            <a href="{!! route('tipoEquipos.edit', [$tipoEquipo->id]) !!}" class='btn btn-warning action-btn edit-btn'><i
                                    class="fa fa-edit"></i></a>
                            {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("Are you sure want to delete this record ?")']) !!}
                        </div>
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>