routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return view('auth.login');
});
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::resource('autos', App\Http\Controllers\AutoController::class);
    Route::get('/compFoto/{id}', [App\Http\Controllers\AutoController::class, 'downloadFoto'])->name('compFoto');

    Route::resource('discoDuros', App\Http\Controllers\DiscoDuroController::class);

    Route::resource('marcaEquipos', App\Http\Controllers\MarcaEquipoController::class);

    Route::resource('modeloEquipos', App\Http\Controllers\ModeloEquipoController::class);

    Route::resource('rams', App\Http\Controllers\RamController::class);

    Route::resource('tipoEquipos', App\Http\Controllers\TipoEquipoController::class);

    Route::resource('documentoAutos', App\Http\Controllers\DocumentoAutoController::class);

    Route::resource('empleados', App\Http\Controllers\EmpleadoController::class);

    Route::resource('equipos', App\Http\Controllers\EquipoController::class);

    Route::resource('mantenimientoAutos', App\Http\Controllers\MantenimientoAutoController::class);

    Route::resource('proyectos', App\Http\Controllers\ProyectoController::class);

    Route::resource('tallers', App\Http\Controllers\TallerController::class);

    Route::resource('tenencias', App\Http\Controllers\TenenciaController::class);

    Route::resource('usuarios', App\Http\Controllers\UsuarioController::class);

    Route::resource('verificacions', App\Http\Controllers\VerificacionController::class);

    Route::resource('arrendadoras', App\Http\Controllers\ArrendadoraController::class);

    Route::resource('contratos', App\Http\Controllers\ContratoController::class);

    Route::get('/tarjeton/{id}', [App\Http\Controllers\DocumentoAutoController::class, 'downloadTarjeton'])->name('tarjeton');

    Route::get('/factura/{id}', [App\Http\Controllers\DocumentoAutoController::class, 'downloadfactura'])->name('factura');
    Route::get('/responsivaempleado/{id}', [App\Http\Controllers\DocumentoAutoController::class, 'downloadresponsivaempleado'])->name('responsivaempleado');
    Route::get('/ultimatenencia/{id}', [App\Http\Controllers\DocumentoAutoController::class, 'downloadultimatenencia'])->name('ultimatenencia');
    Route::get('/ultimaverificacion/{id}', [App\Http\Controllers\DocumentoAutoController::class, 'downloadultimaverificacion'])->name('ultimaverificacion');

});

app/Models/MantenimientoAuto.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class MantenimientoAuto
 * @package App\Models
 * @version June 17, 2021, 5:32 am UTC
 *
 * @property integer $idAuto
 * @property integer $idTaller
 * @property integer $kilometraje
 * @property string $fechaIngreso
 * @property string $fechaEntrega
 * @property string $motivoIngreso
 */
class MantenimientoAuto extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'mantenimientoAutos';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'idAuto',
        'idTaller',
        'kilometraje',
        'fechaIngreso',
        'fechaEntrega',
        'motivoIngreso'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'idAuto' => 'integer',
        'idTaller' => 'integer',
        'kilometraje' => 'integer',
        'fechaIngreso' => 'date',
        'fechaEntrega' => 'date',
        'motivoIngreso' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'idAuto' => 'nullable|integer',
        'idTaller' => 'nullable|integer',
        'kilometraje' => 'nullable|integer',
        'fechaIngreso' => 'nullable',
        'fechaEntrega' => 'nullable',
        'motivoIngreso' => 'nullable|string|max:2000',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'deleted_at' => 'nullable'
    ];

    public function auto()
	{
		return $this->belongsTo(Auto::class, 'idAuto');
	}

	public function tallere()
	{
		return $this->belongsTo(Tallere::class, 'idTaller');
	}

}

app/Http/Controllers/MantenimientoAutoController.php
<?php

namespace App\Http\Controllers;

use Flash;
use Response;
use App\Models\Auto;
use App\Models\Taller;
use Illuminate\Http\Request;
use App\Http\Controllers\AppBaseController;
use App\Repositories\MantenimientoAutoRepository;
use App\Http\Requests\CreateMantenimientoAutoRequest;
use App\Http\Requests\UpdateMantenimientoAutoRequest;

class MantenimientoAutoController extends AppBaseController
{
    /** @var  MantenimientoAutoRepository */
    private $mantenimientoAutoRepository;

    public function __construct(MantenimientoAutoRepository $mantenimientoAutoRepo)
    {
        $this->mantenimientoAutoRepository = $mantenimientoAutoRepo;
    }

    /**
     * Display a listing of the MantenimientoAuto.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $mantenimientoAutos = $this->mantenimientoAutoRepository->all();

        return view('mantenimiento_autos.index')
            ->with('mantenimientoAutos', $mantenimientoAutos);
    }

    /**
     * Show the form for creating a new MantenimientoAuto.
     *
     * @return Response
     */
    public function create()
    {
        $talleres = Taller::pluck('nombreTaller', 'id');

        return view('mantenimiento_autos.create', compact('talleres'));
    }

    /**
     * Store a newly created MantenimientoAuto in storage.
     *
     * @param CreateMantenimientoAutoRequest $request
     *
     * @return Response
     */
    public function store(CreateMantenimientoAutoRequest $request)
    {
        $input = $request->all();

        $mantenimientoAuto = $this->mantenimientoAutoRepository->create($input);

        Flash::success('Mantenimiento añadido.');

        return redirect(route('mantenimientoAutos.index'));
    }

    /**
     * Display the specified MantenimientoAuto.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $mantenimientoAuto = $this->mantenimientoAutoRepository->find($id);

        if (empty($mantenimientoAuto)) {
            Flash::error('Mantenimiento Auto not found');

            return redirect(route('mantenimientoAutos.index'));
        }

        return view('mantenimiento_autos.show')->with('mantenimientoAuto', $mantenimientoAuto);
    }

    /**
     * Show the form for editing the specified MantenimientoAuto.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $mantenimientoAuto = $this->mantenimientoAutoRepository->find($id);

        if (empty($mantenimientoAuto)) {
            Flash::error('Mantenimiento Auto not found');

            return redirect(route('mantenimientoAutos.index'));
        }

        $talleres = Taller::pluck('nombreTaller', 'id');

        return view('mantenimiento_autos.edit', compact('talleres'))->with('mantenimientoAuto', $mantenimientoAuto);
    }

    /**
     * Update the specified MantenimientoAuto in storage.
     *
     * @param int $id
     * @param UpdateMantenimientoAutoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMantenimientoAutoRequest $request)
    {
        $mantenimientoAuto = $this->mantenimientoAutoRepository->find($id);

        if (empty($mantenimientoAuto)) {
            Flash::error('Mantenimiento Auto not found');

            return redirect(route('mantenimientoAutos.index'));
        }

        $mantenimientoAuto = $this->mantenimientoAutoRepository->update($request->all(), $id);

        Flash::success('Mantenimiento actualizado.');

        return redirect(route('mantenimientoAutos.index'));
    }

    /**
     * Remove the specified MantenimientoAuto from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $mantenimientoAuto = $this->mantenimientoAutoRepository->find($id);

        if (empty($mantenimientoAuto)) {
            Flash::error('Mantenimiento Auto not found');

            return redirect(route('mantenimientoAutos.index'));
        }

        $this->mantenimientoAutoRepository->delete($id);

        Flash::success('Mantenimiento eliminado.');

        return redirect(route('mantenimientoAutos.index'));
    }
}

resources/views/mantenimiento_autos/create.blade.php
@extends('layouts.app')
@section('title')
    Mantenimiento Auto
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="m-0 page__heading">Nuevo mantenimiento</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('mantenimientoAutos.index') }}" class="btn btn-primary">Volver</a>
            </div>
        </div>
        <div class="content">
            @include('stisla-templates::common.errors')
            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body ">
                                {!! Form::open(['route' => 'mantenimientoAutos.store']) !!}
                                <div class="row">
                                    @include('mantenimiento_autos.fields')
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/mantenimiento_autos/edit.blade.php
@extends('layouts.app')
@section('title')
    Edit Mantenimiento Auto
@endsection
@section('content')
    <section class="section">
            <div class="section-header">
                <h3 class="page__heading m-0">Edit Mantenimiento Auto</h3>
                <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                    <a href="{{ route('mantenimientoAutos.index') }}"  class="btn btn-primary">Back</a>
                </div>
            </div>
  <div class="content">
              @include('stisla-templates::common.errors')
              <div class="section-body">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-body ">
                                    {!! Form::model($mantenimientoAuto, ['route' => ['mantenimientoAutos.update', $mantenimientoAuto->id], 'method' => 'patch']) !!}
                                        <div class="row">
                                            @include('mantenimiento_autos.fieldsedit')
                                        </div>

                                    {!! Form::close() !!}
                            </div>
                         </div>
                    </div>
                 </div>
              </div>
   </div>
  </section>
@endsection

resources/views/mantenimiento_autos/fields.blade.php
@livewire('kilometros-dependant-select')

<!-- Idtaller Field -->
<div class="form-group col-sm-6">
    {!! Form::label('idTaller', 'Taller:') !!}
    {!! Form::select('idTaller', $talleres, $mantenimientoAuto->idTaller ?? '', ['class' => 'form-control', 'required']); !!}
</div>

<!-- Fechaingreso Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fechaIngreso', 'Fecha ingreso:') !!}
    {!! Form::date('fechaIngreso', null, ['class' => 'form-control', 'id' => 'datepicker', 'required']) !!}
</div>

@push('scripts')
    <script type="text/javascript">
        $('#fechaIngreso').datetimepicker({
            format: 'YYYY-MM-DD',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<script>
    $('#datepicker').datepicker({
        uiLibrary: 'bootstrap4',
        locale: 'es-es',
    });
</script>

<!-- Fechaentrega Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fechaEntrega', 'Fecha entrega:') !!}
    {!! Form::date('fechaEntrega', null, ['class' => 'form-control', 'id' => 'fechaEntrega' , 'required']) !!}
</div>

@push('scripts')
    <script type="text/javascript">
        $('#fechaEntrega').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Motivoingreso Field -->
<div class="form-group col-sm-6">
    {!! Form::label('motivoIngreso', 'Motivo ingreso:') !!}
    {!! Form::text('motivoIngreso', null, ['class' => 'form-control', 'maxlength' => 2000, 'maxlength' => 2000, 'required']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('mantenimientoAutos.index') }}" class="btn btn-light">Cancelar</a>
</div>

resources/views/mantenimiento_autos/fieldsedit.blade.php
@livewire('kilometros-dependant-select', ['idAutoEdit' => $mantenimientoAuto->idAuto])


<!-- Idtaller Field -->
<div class="form-group col-sm-6">
    {!! Form::label('idTaller', 'Taller:') !!}
    {!! Form::select('idTaller', $talleres, $mantenimientoAuto->idTaller ?? '', ['class' => 'form-control', 'required']); !!}
</div>

<!-- Fechaingreso Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fechaIngreso', 'Fecha ingreso:') !!}
    {!! Form::text('fechaIngreso', null, ['class' => 'form-control', 'id' => 'datepicker']) !!}
</div>

@push('scripts')
    <script type="text/javascript">
        $('#fechaIngreso').datetimepicker({
            format: 'YYYY-MM-DD',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<script>
    $('#datepicker').datepicker({
        uiLibrary: 'bootstrap4',
        locale: 'es-es',
    });
</script>

<!-- Fechaentrega Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fechaEntrega', 'Fecha entrega:') !!}
    {!! Form::text('fechaEntrega', null, ['class' => 'form-control', 'id' => 'fechaEntrega']) !!}
</div>

@push('scripts')
    <script type="text/javascript">
        $('#fechaEntrega').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Motivoingreso Field -->
<div class="form-group col-sm-6">
    {!! Form::label('motivoIngreso', 'Motivo ingreso:') !!}
    {!! Form::text('motivoIngreso', null, ['class' => 'form-control', 'maxlength' => 2000, 'maxlength' => 2000]) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('mantenimientoAutos.index') }}" class="btn btn-light">Cancelar</a>
</div>

resources/views/mantenimiento_autos/index.blade.php
@extends('layouts.app')
@section('title')
    Mantenimiento Autos
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Mantenimiento Autos</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('mantenimientoAutos.create') }}" class="btn btn-primary form-btn">Mantenimiento Auto <i
                        class="fas fa-plus"></i></a>
            </div>
        </div>
        @include('flash::message')
        <div class="section-body">
            <div class="card">
                <div class="card-body">
                    @include('mantenimiento_autos.table')
                </div>
            </div>
        </div>

    </section>
@endsection

resources/views/mantenimiento_autos/show.blade.php
@extends('layouts.app')
@section('title')
    Mantenimiento Auto Details 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
        <h1>Mantenimiento Auto Details</h1>
        <div class="section-header-breadcrumb">
            <a href="{{ route('mantenimientoAutos.index') }}"
                 class="btn btn-primary form-btn float-right">Back</a>
        </div>
      </div>
   @include('stisla-templates::common.errors')
    <div class="section-body">
           <div class="card">
            <div class="card-body">
                    @include('mantenimiento_autos.show_fields')
            </div>
            </div>
    </div>
    </section>
@endsection

resources/views/mantenimiento_autos/show_fields.blade.php
<!-- Idauto Field -->
<div class="form-group">
    {!! Form::label('idAuto', 'Idauto:') !!}
    <p>{{ $mantenimientoAuto->idAuto }}</p>
</div>

<!-- Idtaller Field -->
<div class="form-group">
    {!! Form::label('idTaller', 'Idtaller:') !!}
    <p>{{ $mantenimientoAuto->idTaller }}</p>
</div>

<!-- Kilometraje Field -->
<div class="form-group">
    {!! Form::label('kilometraje', 'Kilometraje:') !!}
    <p>{{ $mantenimientoAuto->kilometraje }}</p>
</div>

<!-- Fechaingreso Field -->
<div class="form-group">
    {!! Form::label('fechaIngreso', 'Fechaingreso:') !!}
    <p>{{ $mantenimientoAuto->fechaIngreso }}</p>
</div>

<!-- Fechaentrega Field -->
<div class="form-group">
    {!! Form::label('fechaEntrega', 'Fechaentrega:') !!}
    <p>{{ $mantenimientoAuto->fechaEntrega }}</p>
</div>

<!-- Motivoingreso Field -->
<div class="form-group">
    {!! Form::label('motivoIngreso', 'Motivoingreso:') !!}
    <p>{{ $mantenimientoAuto->motivoIngreso }}</p>
</div>

resources/views/mantenimiento_autos/table.blade.php
<div class="table-responsive">
    <table class="table" id="dtBasicExample">
        <thead>
            <tr>
                <th>Auto</th>
                <th>Taller</th>
                <th>Kilometraje</th>
                <th>Fecha ingreso</th>
                <th>Fecha entrega</th>
                <th>Motivo ingreso</th>
                <th>Acción</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($mantenimientoAutos as $mantenimientoAuto)
                <tr>
                    <td>
                        @php
                            $auto = DB::table('autos')->find($mantenimientoAuto->idAuto)
                        @endphp
                        {{ $auto->placas}}
                    </td>
                    <td>{{ $mantenimientoAuto->tallere->nombreTaller }}</td>
                    <td>{{ $mantenimientoAuto->kilometraje }}</td>
                    <td>{{ $mantenimientoAuto->fechaIngreso }}</td>
                    <td>{{ $mantenimientoAuto->fechaEntrega }}</td>
                    <td>{{ $mantenimientoAuto->motivoIngreso }}</td>
                    <td class="text-center ">
                        {!! Form::open(['route' => ['mantenimientoAutos.destroy', $mantenimientoAuto->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                            {{-- <a href="{!! route('mantenimientoAutos.show', [$mantenimientoAuto->id]) !!}" class='btn btn-light action-btn '><i
                                    class="fa fa-eye"></i></a> --}}
                            <a href="{!! route('mantenimientoAutos.edit', [$mantenimientoAuto->id]) !!}" class='btn btn-warning action-btn edit-btn'><i
                                    class="fa fa-edit"></i></a>
                            {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("Are you sure want to delete this record ?")']) !!}
                        </div>
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>